name: "Integration Test"

on:
  push:
    # Dependabot has no access to the secrets that this workflow requires. So we
    # skip running the workflow in branches that dependabot presumably created.
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Git Project"
        uses: "actions/checkout@v5"

      - name: "Setup Go Env"
        uses: "actions/setup-go@v5"
        with:
          cache: true
          go-version: "1.24.0"

      - name: "Check Go Tests"
        env:
          ROGHFS_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          go test -tags=integration -v -race
